# Copyright (c) 2026 Amit Chougule. All rights reserved.
# Dev/CI only. Service scrape targets are added in Phase 12.
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
